window.HORIZON_CONFIG = {
  storageKey: "horyzont_onovlennya_mvp_v1",
  currentParticipantKey: "horyzont_current_participant_v1",
  teamSessionKey: "horyzont_team_session_v1",
  teamAccessCode: "team",
  cycles: [
    {
      id: "cycle-2026-07",
      title: "21.07.26 - 30.07.26",
      dates: "21 липня - 30 липня 2026",
      capacity: 24,
      status: "Набір відкрито",
    },
    {
      id: "cycle-2026-08",
      title: "18.08.26 - 27.08.26",
      dates: "18 серпня - 27 серпня 2026",
      capacity: 24,
      status: "Попередній список",
    },
    {
      id: "cycle-2026-09",
      title: "08.09.26 - 17.09.26",
      dates: "8 вересня - 17 вересня 2026",
      capacity: 24,
      status: "Попередній список",
    },
  ],
  participantStatuses: [
    "Нова заявка",
    "Підтверджено",
    "Очікує уточнення",
    "У циклі",
    "Завершив програму",
  ],
  questionnaires: [
    {
      id: "entry-wellbeing",
      version: "2026-07-draft-1",
      stage: "Вхід",
      title: "Вхідна оцінка самопочуття",
      description: "Базовий вимір перед початком циклу.",
      fields: [
        {
          id: "wellbeingScore",
          label: "Оцініть поточне самопочуття",
          type: "scale",
          min: 1,
          max: 10,
          defaultValue: 6,
          minLabel: "дуже важко",
          maxLabel: "стабільно",
          required: true,
        },
        {
          id: "sleepQuality",
          label: "Якість сну протягом останнього тижня",
          type: "radio",
          options: ["Погана", "Нестабільна", "Задовільна", "Добра"],
          required: true,
        },
        {
          id: "mainRequest",
          label: "З чим найважливіше попрацювати під час програми?",
          type: "textarea",
          required: false,
        },
      ],
    },
    {
      id: "entry-questionnaire-1",
      version: "2026-07-placeholder",
      stage: "Вхід",
      title: "Опитувальник 1",
      description: "Структуру питань фонд надасть окремо.",
      fields: [
        {
          id: "q1PlaceholderScale",
          label: "Чернетковий показник для першого опитувальника",
          type: "scale",
          min: 1,
          max: 10,
          defaultValue: 5,
          minLabel: "низько",
          maxLabel: "високо",
          required: true,
        },
        {
          id: "q1Comment",
          label: "Коментар до відповіді",
          type: "textarea",
          required: false,
        },
      ],
    },
    {
      id: "entry-questionnaire-2",
      version: "2026-07-placeholder",
      stage: "Вхід",
      title: "Опитувальник 2",
      description: "Структуру питань фонд надасть окремо.",
      fields: [
        {
          id: "q2PlaceholderScale",
          label: "Чернетковий показник для другого опитувальника",
          type: "scale",
          min: 1,
          max: 10,
          defaultValue: 5,
          minLabel: "низько",
          maxLabel: "високо",
          required: true,
        },
        {
          id: "q2SupportNeed",
          label: "Потреба у додатковому супроводі",
          type: "radio",
          options: ["Ні", "Потрібно уточнити", "Так"],
          required: true,
        },
      ],
    },
    {
      id: "exit-objective",
      version: "2026-07-draft-1",
      stage: "Вихід",
      title: "Вихідна об'єктивна анкета",
      description: "Повторний вимір після завершення циклу.",
      fields: [
        {
          id: "wellbeingScoreExit",
          label: "Оцініть самопочуття після циклу",
          type: "scale",
          min: 1,
          max: 10,
          defaultValue: 8,
          minLabel: "дуже важко",
          maxLabel: "стабільно",
          required: true,
        },
        {
          id: "sleepQualityExit",
          label: "Якість сну після циклу",
          type: "radio",
          options: ["Погана", "Нестабільна", "Задовільна", "Добра"],
          required: true,
        },
      ],
    },
    {
      id: "exit-subjective",
      version: "2026-07-draft-1",
      stage: "Вихід",
      title: "Суб'єктивний відгук",
      description: "Враження учасника про програму.",
      fields: [
        {
          id: "satisfaction",
          label: "Загальна оцінка програми",
          type: "scale",
          min: 1,
          max: 10,
          defaultValue: 9,
          minLabel: "потребує змін",
          maxLabel: "дуже корисно",
          required: true,
        },
        {
          id: "feedback",
          label: "Що було найкориснішим?",
          type: "textarea",
          required: false,
        },
      ],
    },
  ],
};
